task = 'Take Med Daily'
print(task)
print (id(task))
print(task[0])
print(task[13])
print(task[-14])
print(task[-1])
print(task[0:1])
print(task[0:2])
print(task[-14:-13])
print(task[-14:-12])
print(task[:])
print(task[:3])
print(task[3:])