print(int(False))
print(int(True))
print(int(2.3))
print(int('10'))
print(int('1'))
print(int('one'))

print(float(2))
print(float('two'))

print(complex(10))
print(complex(10,20))
print(complex(2.3,5.6))
print(complex(2.3,5))
print(complex(False,False))
print(complex(True, True))
print(complex(False,True))
print(complex(10,20,30))

print(bool(1))
print(bool(1.1))
print(bool(11+1j))
print(bool('nit'))
print(bool())
print(bool(0))

print(str(2))
print(str('True'))
print(str(1+2j))
print(str(2.2))